import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SearchOutlined } from '@ant-design/icons';
import Link from 'next/link';
import Image from 'next/image';
import "./globals.css";
import AntdClientComponents from './components/AntdClientComponents';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="header" aria-label="Main Navigation">
          <button className="menu-icon" aria-label="Open Menu">☰</button>
          <h1 className="app-title">Samriddhi Setu</h1>
          <div className="profile-icon" aria-label="User Profile">
            <Image src="/profile-avatar.png" alt="User Profile" width={40} height={40} />
          </div>
        </header>
        <main className="main-content" role="main">
          <AntdClientComponents>
            {children}
          </AntdClientComponents>
        </main>
        <footer className="footer" aria-label="Footer Navigation">
          <nav className="footer-nav" aria-label="Footer Links">
            <Link href="/home">
              <span className="nav-icon" aria-label="Home">🏠</span>
            </Link>
            <Link href="/events">
              <span className="nav-icon" aria-label="Events">📅</span>
            </Link>
            <Link href="/forums">
              <span className="nav-icon" aria-label="Forums">💬</span>
            </Link>
            <Link href="/settings">
              <span className="nav-icon" aria-label="Settings">⚙️</span>
            </Link>
          </nav>
          <p>&copy; {new Date().getFullYear()} Samriddhi Setu. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
